# Source: https://github.blog/2023-01-11-passwordless-deployments-to-the-cloud/
# https://learn.microsoft.com/en-us/azure/active-directory/develop/workload-identity-federation
# https://learn.microsoft.com/en-us/azure/active-directory/develop/workload-identity-federation-create-trust?pivots=identity-wif-apps-methods-azp
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions

name: Validate_Azure_Credentials_V2

on: workflow_dispatch

permissions:
  id-token: write

jobs:

  Validate-Azure-Credentials-OIDC:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION }}

  Trigger-API-SendEmail:
    if: ${{ failure() }}
    needs:  Validate-Azure-Credentials-OIDC
    runs-on: ubuntu-latest
    steps:
      - name: call httprequest_action v2
        uses: oaviles/httprequest_action@v2
        with:
          url: ${{ secrets.API_URL }}
          path: ${{ secrets.API_PATH }}
          key: ${{ secrets.API_KEY }}
        
      - name: Get the output status
        run: echo "Status Code ${{ steps.javascriptaction.outputs.status }}"
        
  Azure-Credential-is-Working:
    if: ${{ success() }}
    needs:  Validate-Azure-Credentials-OIDC
    runs-on: ubuntu-latest
    steps:
      - name: Azure Credential OIDC is Working
        run: echo Azure Credential OIDC is Working!
